### PR TITLE
Fix deserialization types

### PR DESCRIPTION
**Pull request by gabfeldman**
Hi,
I'm keen to use this library. I found this small issue with private get instruments. Can we merge it?
Thanks

### CODE REVIEW

**Comment by badokun** [comment]
@gabfeldman it seems @psollberger is not actively maintaining this repository. I'm considering using this, but if the project is dead I may need to keep looking....

**Comment by badokun** [comment]
@gabfeldman I've merged your change (and the other open pull request in this repo) to my fork. Would be good to maintain/contribute any changes to one repo for everyone's benefit (https://github.com/pinostrats/DeriSock)

**Comment by psollberger** [comment]
Somehow i didn't notice that there was any PR or comment. I'm very sorry for that.

**Comment by badokun** [comment]
@psollberger I see you've taken care of the open pull requests, thanks. I may look at bumping the project to .net 6 on my forked repo. Is that something you've considered/be interested in?

**Comment by psollberger** [comment]
@badokun My idea was to make the library compatible for as many environments as possible hence the netcoreapp2.1 TFM

I would be interested in bumping to netcoreapp3.1 and possibliy do a multi-target build that also builds .net 6 specifically

I'm not sure about the best-practices in this regard but i'm open for any suggestions

**Comment by badokun** [comment]
@psollberger I'm not sure what's the best/recommended approach for what you're aiming to do. The project I'm working on is already on .net 6.0 so I've updated each project's version, and bumped all the nuget packages. There were no breaking changes fortunately.

**Comment by psollberger** [comment]
@badokun i started to change it to a multi-target project targeting: netstandard2.1 netstandard2.0 netstandard1.3 net45 net46 net5.0 and net6.0 (inspired from Serilog)

There are some dependency problems I need to resolve though

**Comment by badokun** [comment]
Awesome, thanks for taking the time. The library seems very comprehensive and well documented. Good to see it maintained for the greater good

**Pull request merged**
