### PR TITLE
Update SubscribeInstrumentTrades<PublicTrade> to <PublicTrade[]>

### PR DESCRIPTION
**Pull request by Tradyn**
Update SubscribeInstrumentTrades<PublicTrade> to <PublicTrade[]>

### CODE REVIEW

**Comment by psollberger** [comment]
Unfortunately I can't merge this PR because it contains edits of generated files.
Those changes will be overwritten the next time the files are generated.

If there is something wrong in generated files, the API documentation errors need to be fixed in one of the override files located at https://github.com/psollberger/DeriSock/tree/main/src/DeriSock.DevTools/Data

**Comment by Tradyn** [comment]
Hey, If you can tell me how to change the auto gen files I can do it myself

Changes I made are minimal so it can be done by hand easily.

There are not many changes, just lots of commits where I changed some things back to original.

**Comment by psollberger** [comment]
I already pushed the change regarding the return type to user.changes subscriptions.

The change to the `ComboType` enumearation will not do anything meaningful on it's own.
A mapping is needed in `InternalStringExtensions.ComboTypeMap` for it to make any sense.

`ComboLeg` just does not contain a trade direction. The trade direction is only applicable when setting up the notification. That's why two separate types exist for that. What use-case will be easier if there is only one type?

**Comment by Tradyn** [comment]
To build a combo client side you have to use comborequest, but you need to wrap it in <Combo> to store ID of combo... but that uses ComboLegs..

If the same object for comborequest and comboleg is used you can re-use the Combo object to make and receive combos...

**Comment by psollberger** [comment]
You'll have to transform the list anyway, because `/public/get_combos` doesn't contain the required `direction` for the `/private/create_combo` method.

How do you deal with that?

**Comment by Tradyn** [comment]
Add direction as a nullable property.
Then it can be used for both

**Comment by psollberger** [comment]
That's not what I meant. You can not use the ComboLeg from `/public/get_combos` as a parameter in `/private/create_combo`. You have to add the `direction` and change the `amount` as well. I see no benefit in mergin the two types.

**Pull request closed without merging**
