### PR TITLE
Connection handling Improvements. Fixes #65, fixes #66

### LINKED ISSUE #65: Problem when there is a loss (break) of communication with the API server socket
Good afternoon!
There is a serious problem when there is a loss (break) of communication with the API server socket (especially when the connection is disconnected for a long time) in the handler for receiving messages by subscriptions and the handler for sending messages (class: DefaultJsonRpcMessageSource  methods: Send() and GetMessageStream()). When the connection is broken, work is obtained in endless loops, which greatly increases the load on the computer processor, while the software application using the SDK does not receive information about the connection break through the "Disconnected" event ...

At the moment I'm solving this problem in this way:

Bug GetMessageStream

This allows you to break out of the infinite loop, and send a message to the user application about the "Disconnected" event.

### LINKED ISSUE #66: Issue reconnecting to API server socket when using DefaultJsonRpcMessageSource.Reconnect() method
Now, when the DefaultJsonRpcMessageSource.Reconnect() method is executed, a connection is made to a new API server socket, and as a result of this change, all subscriptions (public and user) to events made in the user application and using this SDK are lost.

When executing this method:

1. There is no restoration of subscriptions to data streams that were made when using the previous socket. 
       
     We kindly request:
 Add the restoration of subscriptions that were created when connecting via the previous socket. If this is not done, then the whole point of using subscriptions disappears, since streams are periodically interrupted, and this, accordingly, leads to an uncontrolled stop of the correct operation of the user application.

2. The user application does not receive messages about the loss and subsequent change of connection to the API server. 
      
      Request: 
Add the ability to subscribe to the "Reconnect" event to the DeribitClient class so that the user application has the ability to timely monitor the health of subscriptions to streaming events.

### PR DESCRIPTION
**Pull request by psollberger**
- Renamed/Moved `DeriSock.Net.JsonRpc.DefaultJsonRpcMessageSource` to `DeriSock.Net.TextMessageWebSocketClient`
- `TextMessageWebSocketClient` no longer handles re-connecting. This was moved to `DeribitClient`
- `ITextMessageClient` (which replaces `IJsonRpcMessageSource`) can (and is) now be used for unit testing
- `DeribitClient` now contains the events `ConnectionLost` and `ConnectionRestored` which are triggered during re-connecting

To control re-connecting the following properties are now available on `DeribitClient`:
- ReConnectDelay (default: 1s)
How much time must have been passed before trying to connect again
- ReConnectDelayIncreaseFactor (default: 2.0)
After a re-connect attempt failed, how much will the `ReConnectDelay` be increased
- ReConnectMaxAttempts (default: 5)
How many times a re-connect will be tried before giving up.

### CODE REVIEW

**Comment by psollberger** [comment]
Hi @AndreyVasilchenko

I invite you to check out this changes and tell me wheter they solve your issues #65 and #66 

Thanks

**Comment by AndreyVasilchenko** [comment]
Good afternoon!

Thank you very much for your attention to the problems I have identified. I will definitely check the changes you made and let you know the result. But, the truth is, I can do it not earlier than in a couple of weeks.

Thanks again.

**Comment by psollberger** [comment]
To get this exception, the connection is either never established, not yet fully established or purposfully disconnected.

The only place where the `IsConnected` property of the `TextMessageWebSocketClient` is set to `false` is in its `Disconnect` method. The `Connect` method sets the property to `true` after the socket is connected.

Only when `IsConnected` is `false` this exception is thrown.

**Comment by InTheta** [comment]
It runs for 10-30 mins all subscriptions working before throwing this error.
Bot is currently broken and unable to run.
Any ideas?
Is the connecting code still the same?

**Comment by InTheta** [comment]
image

**Pull request merged**
