### PR TITLE
Update UnderlyingIndex's data type from decimal to string

### PR DESCRIPTION
**Pull request by badokun**

### CODE REVIEW

**Comment by psollberger** [comment]
Thank you for your contribution.

According to the documentation for:
- [public/get_order_book](https://docs.deribit.com/#public-get_order_book)
- [public/ticker](https://docs.deribit.com/#public-ticker)
- [incremental_ticker.{instrument_name}](https://docs.deribit.com/#incremental_ticker-instrument_name)
- [ticker.{instrument_name}.{interval}](https://docs.deribit.com/#ticker-instrument_name-interval)

The data type for `underlying_index` is indeed a number.

That will affect the three types you adjusted in the PR.

Only for the following responses the data type for `underlying_index` is a string:
- [public/get_book_summary_by_currency](https://docs.deribit.com/#public-get_book_summary_by_currency)
- [public/get_book_summary_by_instrument](https://docs.deribit.com/#public-get_book_summary_by_instrument)

This is handled in the `BookSummary` type and the field is indeed a string there.

Is it possible that the documentation from Deribit itself is wrong and they deliver the wrong data type in the requests mentioned above?

**Comment by badokun** [comment]
It appears their documentation is wrong. Even the wording is conflicting. Describing the `underlying_index` property it says: "Name of the underlying future, or index_price (options only)". Name indicating a string, not a number.

Regardless, I tested the responses using their test console https://test.deribit.com/api_console/?method=%2Fpublic%2Fticker and the value returned is a string.

**Comment by psollberger** [comment]
To be sure I will check all the requests this evening and make sure that none of the requests returns a number.
If that's all good i'll merge the PR.

Maybe I get a response to the ticket too.

**Comment by badokun** [comment]
Thanks!

**Pull request merged**
